=== mokshasoul/XML-Praktikum/db/apps/praktikum/schemas/CalendarXEvents.xsd
<!-- 6 May 2015 --><!-- Sub-schema for collections of events, extracted from Conceptual Model Calendar Data Vs 1.7 --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"><xs:element name="events" type="Events"/><xs:complexType name="Events"><xs:sequence minOccurs="1" maxOccurs="unbounded"><xs:element name="event" type="Event"/></xs:sequence></xs:complexType><xs:complexType name="Event"><xs:all><xs:element name="location" type="Location" minOccurs="0" maxOccurs="1"/><xs:element name="attendees"><xs:complexType><xs:sequence><xs:element name="attendee" type="Contact" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/><xs:attribute name="categories" type="Categories" use="required"/><xs:attribute name="date" type="xs:date" use="required"/><xs:attribute name="startTime" type="xs:time" use="required"/><xs:attribute name="endTime" type="xs:time" use="required"/><xs:attribute name="note" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Location"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Contact"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:simpleType name="Categories"><xs:list itemType="Category"/></xs:simpleType><xs:simpleType name="Category"><xs:restriction base="xs:string"><xs:enumeration value="work"/><xs:enumeration value="music"/></xs:restriction></xs:simpleType></xs:schema>

=== mokshasoul/XML-Praktikum/db/apps/praktikum/data/events.xml
<?xml-stylesheet type="text/xsl" href="SimpleEvents.xsl" ?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CalendarXEvents.xsd">
    <event description="PraktXMLT" categories="work" date="2015-05-07" startTime="10:15:00"
        endTime="12:00:00" note="">
        <attendees>
            <attendee description="Anne Br端ggemann-Klein"/>
        </attendees>
        <location description="01.07.023"/>
    </event>
    <event description="VorlEP" categories="work" date="2015-05-04" startTime="12:15:00"
        endTime="13:45:00" note="">
        <attendees>
            <attendee description="Anne Br端ggemann-Klein"/>
        </attendees>
    </event>
    <event description="OChrHFP" categories="music" date="2015-05-08" startTime="20:00:00"
        endTime="22:00:00" note="">
        <attendees>
            <attendee description="Anne Br端ggemann-Klein"/>
            <attendee description="Orchesterleitung"/>
        </attendees>
    </event>
    <event description="OChrHFP" categories="music" date="2015-06-08" startTime="20:00:00"
        endTime="22:00:00" note="">
        <attendees>
            <attendee description="Anne Br端ggemann-Klein"/>
            <attendee description="Orchesterleitung"/>
        </attendees>
    </event>
    <event description="John" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendee description="Test"/>
        <location description="Test"/>
    </event>
    <event description="John" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendee description="Test"/>
        <location description="Test"/>
    </event>
    <event description="John" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendee description="Test"/>
        <location description="Test"/>
    </event>
    <event description="LOOOOL" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendee description="Test"/>
        <location description="Test"/>
    </event>
    <event description="JLOOOL" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendee description="Test"/>
        <location description="Test"/>
    </event>
    <event description="JLOOOL" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendees>
            <attendee description="Test"/>
        </attendees>
        <location description="Test"/>
    </event>
    <event description="dsadas" categories="lol" date="2015-07-08" startTime="10:15:00"
        endTime="10:15:00" note="Test">
        <attendees>
            <attendee description="Test"/>
        </attendees>
        <location description="Test"/>
    </event>
    <event description="" categories="" date="" startTime="" endTime="" note="">
        <attendees/>
        <location description=""/>
    </event>
    <event description="Test1234" categories="Test1234" date="2015-07-21" startTime="10:00:00"
        endTime="10:30:00" note="Test1234">
        <attendees>
            <attendee description="Test1234"/>
        </attendees>
        <location description="Test1234"/>
    </event>
</events>

=== mokshasoul/XML-Praktikum/XSLT/sampleEvents.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SimpleEvents.xsl" ?>

<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="CalendarXEvents.xsd">
	<event description="PraktXMLT" categories="work" date="2015-05-07"
		startTime="10:15:00" endTime="12:00:00" note="">
		<attendees>
			<attendee description="Anne Brüggemann-Klein"/>
		</attendees>
		<location description="01.07.023"/>
	</event>
	<event description="VorlEP" categories="work" date="2015-05-04"
		startTime="12:15:00" endTime="13:45:00" note="">
		<attendees>
			<attendee description="Anne Brüggemann-Klein"/>
		</attendees>
	</event>
	<event description="OChrHFP" categories="music" date="2015-05-08"
		startTime="20:00:00" endTime="22:00:00" note="">
		<attendees>
			<attendee description="Anne Brüggemann-Klein"/>
			<attendee description="Orchesterleitung"/>
		</attendees>
	</event>
</events>
