=== mokshasoul/XML-Praktikum/db/apps/praktikum/schemas/CalendarX.xsd
<!-- 11 June 2012 --><!-- For Conceptual Model Calendar Data Vs 1.7, 21 May 2013 --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"><xs:element name="calendarX" type="CalendarX"><xs:annotation><xs:documentation> Uniqueness constraints relate to the description attribute. (1) There
                is only one CalendarX element in the system, so its description attribute is
                automatically unique for CalendarX objects. (2) Event objects are not identified
                through their description attribute. The description attribute of Event objects
                takes its value from the description attribute of the indirectly related SuperEvent
                object. (3) Objects of other types that have a description attribute are uniquely
                identified by their description attribute. For example, all objects of type User
                need to be identified by their descriptions, but description values of User objects
                and of Pattern objects may be identical.</xs:documentation><xs:documentation>The following elements refer to description attributes of other
                elements: owner, location, attendee, definedBy, recurrencePattern, firstPattern, furtherPattern.
                Referential integrity is guaranteed by xs:keyRef constraints.</xs:documentation></xs:annotation><xs:key name="UserKey"><xs:selector xpath=".//users/user"/><xs:field xpath="@description"/></xs:key><xs:key name="CalendarKey"><xs:selector xpath=".//calendars/calendar"/><xs:field xpath="@description"/></xs:key><xs:key name="SuperEventKey"><xs:selector xpath=".//superEvents/superEvent"/><xs:field xpath="@description"/></xs:key><xs:key name="EventRuleKey"><xs:selector xpath=".//eventRules/eventRule"/><xs:field xpath="@description"/></xs:key><xs:key name="PatternKey"><xs:annotation><xs:documentation>XPath 1.0 is not compatible with substitution groups. Hence we use
                    * rather than the more specific "anything in the head group of
                    pattern".</xs:documentation></xs:annotation><xs:selector xpath=".//patterns/*"/><xs:field xpath="@description"/></xs:key><xs:key name="LocationKey"><xs:selector xpath=".//locations/location"/><xs:field xpath="@description"/></xs:key><xs:key name="ContactKey"><xs:selector xpath=".//contacts/contact"/><xs:field xpath="@description"/></xs:key>
        <!-- 
        owner, location, attendee, definedBy, recurrencePattern, firstPattern, furtherPattern
        --><xs:keyref refer="UserKey" name="Calendar2Owner"><xs:selector xpath=".//calendar/owner"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="LocationKey" name="EventRule2Location"><xs:selector xpath=".//eventRule/location"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="ContactKey" name="EventRule2Contact"><xs:selector xpath=".//eventRule/attendees/attendee"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="EventRuleKey" name="Event2EventRule"><xs:selector xpath=".//event/definedBy"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="EventRuleKey" name="Event2Location"><xs:selector xpath=".//event/location"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="EventRuleKey" name="Event2Contact"><xs:selector xpath=".//event/attendees/attendee"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="PatternKey" name="EventRule2Pattern"><xs:selector xpath=".//eventRule/recurrencePattern"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="PatternKey" name="ComplexPattern2PatternFirst"><xs:selector xpath=".//firstPattern"/><xs:field xpath="."/></xs:keyref><xs:keyref refer="PatternKey" name="ComplexPattern2PatternFurther"><xs:selector xpath=".//furtherPattern"/><xs:field xpath="."/></xs:keyref></xs:element><xs:complexType name="CalendarX"><xs:all><xs:element name="users"><xs:complexType><xs:sequence><xs:element name="user" type="User" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element><xs:element name="calendars"><xs:complexType><xs:sequence><xs:element name="calendar" type="Calendar" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element><xs:element name="patterns"><xs:complexType><xs:sequence><xs:element ref="pattern" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element><xs:element name="contacts"><xs:complexType><xs:sequence><xs:element name="contact" type="Contact" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element><xs:element name="locations"><xs:complexType><xs:sequence><xs:element name="location" type="Location" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Calendar"><xs:all><xs:element name="owner" type="xs:string" minOccurs="0" maxOccurs="1"/><xs:element name="superEvents"><xs:complexType><xs:sequence><xs:element name="superEvent" type="SuperEvent" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:complexType name="User"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:complexType name="SuperEvent"><xs:all><xs:element name="eventRules"><xs:complexType><xs:sequence><xs:element name="eventRule" type="EventRule" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/><xs:attribute name="categories" type="Categories" use="required"/></xs:complexType><xs:complexType name="EventRule"><xs:all><xs:element name="recurrencePattern" type="xs:string"/><xs:element name="location" type="xs:string" minOccurs="0" maxOccurs="1"/><xs:element name="attendees"><xs:complexType><xs:sequence><xs:element name="attendee" type="xs:string" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/><xs:attribute name="startTime" type="xs:time" use="required"/><xs:attribute name="endTime" type="xs:time" use="required"/><xs:attribute name="note" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Event"><xs:all><xs:element name="definedBy" type="xs:string" minOccurs="0" maxOccurs="1"/><xs:element name="location" type="xs:string" minOccurs="0" maxOccurs="1"/><xs:element name="attendees"><xs:complexType><xs:sequence><xs:element name="attendee" type="xs:string" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:all><xs:attribute name="description" type="xs:string" use="required"/><xs:attribute name="categories" type="Categories" use="required"/><xs:attribute name="date" type="xs:date" use="required"/><xs:attribute name="startTime" type="xs:time" use="required"/><xs:attribute name="endTime" type="xs:time" use="required"/><xs:attribute name="note" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Pattern" abstract="true"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:element name="pattern" type="Pattern" abstract="true"/><xs:complexType name="ComplexPattern" abstract="true"><xs:complexContent><xs:extension base="Pattern"><xs:sequence><xs:element name="firstPattern" type="xs:string"/><xs:element name="furtherPatterns"><xs:complexType><xs:sequence><xs:element name="furtherPattern" type="xs:string" minOccurs="0" maxOccurs="unbounded"/></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:extension></xs:complexContent></xs:complexType><xs:element name="complexPattern" type="ComplexPattern" abstract="true" substitutionGroup="pattern"/><xs:complexType name="UnionPattern"><xs:complexContent><xs:extension base="ComplexPattern"/></xs:complexContent></xs:complexType><xs:element name="unionPattern" type="UnionPattern" substitutionGroup="complexPattern"/><xs:complexType name="IntersectionPattern"><xs:complexContent><xs:extension base="ComplexPattern"/></xs:complexContent></xs:complexType><xs:element name="intersectionPattern" type="IntersectionPattern" substitutionGroup="complexPattern"/><xs:complexType name="DifferencePattern"><xs:complexContent><xs:extension base="ComplexPattern"/></xs:complexContent></xs:complexType><xs:element name="differencePattern" type="DifferencePattern" substitutionGroup="complexPattern"/><xs:complexType name="SimplePattern" abstract="true"><xs:complexContent><xs:extension base="Pattern"><xs:attribute name="startDate" type="xs:date" use="optional"/><xs:attribute name="endDate" type="xs:date" use="optional"/><xs:attribute name="frequency" type="xs:nonNegativeInteger" default="1" use="optional"><xs:annotation><xs:documentation>There will always be a value for this attribute, although
                            it is declared as optional, because of the default
                            value.</xs:documentation></xs:annotation></xs:attribute></xs:extension></xs:complexContent></xs:complexType><xs:element name="simplePattern" type="SimplePattern" abstract="true" substitutionGroup="pattern"/><xs:complexType name="DailyPattern"><xs:complexContent><xs:extension base="SimplePattern"/></xs:complexContent></xs:complexType><xs:element name="dailyPattern" type="DailyPattern" substitutionGroup="simplePattern"/><xs:complexType name="WeeklyPattern"><xs:complexContent><xs:extension base="SimplePattern"><xs:attribute name="dayOfWeek" type="DayOfWeek" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="weeklyPattern" type="WeeklyPattern" substitutionGroup="simplePattern"/><xs:complexType name="MonthlyPattern" abstract="true"><xs:complexContent><xs:extension base="SimplePattern"/></xs:complexContent></xs:complexType><xs:element name="monthlyPattern" type="MonthlyPattern" substitutionGroup="simplePattern"/><xs:complexType name="CardinalMonthlyPattern"><xs:complexContent><xs:extension base="MonthlyPattern"><xs:attribute name="dayOfMonth" type="DayOfMonth" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="cardinalMonthlyPattern" type="CardinalMonthlyPattern" substitutionGroup="monthlyPattern"/><xs:complexType name="OrdinalMonthlyPattern"><xs:complexContent><xs:extension base="MonthlyPattern"><xs:attribute name="ordinal" type="Ordinal" use="required"/><xs:attribute name="dayType" type="DayType" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="ordinalMonthlyPattern" type="OrdinalMonthlyPattern" substitutionGroup="monthlyPattern"/><xs:complexType name="YearlyPattern" abstract="true"><xs:complexContent><xs:extension base="SimplePattern"><xs:attribute name="month" type="Month" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="yearlyPattern" type="YearlyPattern" substitutionGroup="simplePattern"/><xs:complexType name="CardinalYearlyPattern"><xs:complexContent><xs:extension base="YearlyPattern"><xs:attribute name="dayOfMonth" type="DayOfMonth" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="cardinalYearlyPattern" type="CardinalYearlyPattern" substitutionGroup="yearlyPattern"/><xs:complexType name="OrdinalYearlyPattern"><xs:complexContent><xs:extension base="YearlyPattern"><xs:attribute name="ordinal" type="Ordinal" use="required"/><xs:attribute name="dayType" type="DayType" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:element name="ordinalYearlyPattern" type="OrdinalYearlyPattern" substitutionGroup="yearlyPattern"/><xs:complexType name="Location"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:complexType name="Contact"><xs:attribute name="description" type="xs:string" use="required"/></xs:complexType><xs:simpleType name="Categories"><xs:list itemType="xs:Name"/></xs:simpleType><xs:simpleType name="DayType"><xs:restriction base="xs:string"><xs:enumeration value="day"/><xs:enumeration value="weekDay"/></xs:restriction></xs:simpleType><xs:simpleType name="Ordinal"><xs:restriction base="xs:string"><xs:enumeration value="first"/><xs:enumeration value="second"/><xs:enumeration value="third"/><xs:enumeration value="fourth"/><xs:enumeration value="penultimate"/><xs:enumeration value="ultimate"/></xs:restriction></xs:simpleType><xs:simpleType name="DayOfWeek"><xs:restriction base="xs:string"><xs:enumeration value="Monday"/><xs:enumeration value="Tuesday"/><xs:enumeration value="Wednesday"/><xs:enumeration value="Thursday"/><xs:enumeration value="Friday"/><xs:enumeration value="Saturday"/><xs:enumeration value="Sunday"/></xs:restriction></xs:simpleType><xs:simpleType name="Month"><xs:restriction base="xs:string"><xs:enumeration value="January"/><xs:enumeration value="February"/><xs:enumeration value="March"/><xs:enumeration value="April"/><xs:enumeration value="May"/><xs:enumeration value="June"/><xs:enumeration value="July"/><xs:enumeration value="August"/><xs:enumeration value="September"/><xs:enumeration value="October"/><xs:enumeration value="November"/><xs:enumeration value="December"/></xs:restriction></xs:simpleType><xs:simpleType name="DayOfMonth"><xs:restriction base="xs:nonNegativeInteger"><xs:minInclusive value="1"/><xs:maxInclusive value="31"/></xs:restriction></xs:simpleType></xs:schema>

=== mokshasoul/XML-Praktikum/db/apps/praktikum/data/sampleCalendarX.xml
<calendarX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/CalendarX.xsd" description="Demonstrating super events"><calendars><calendar description="Demonstrating super events"><superEvents><superEvent description="XMLT20155" categories="teaching"><eventRules><eventRule description="XMLT20155_1" startTime="10:20:00" endTime="12:15:00" note=""><recurrencePattern>XMLT20155_1</recurrencePattern><attendees/></eventRule></eventRules></superEvent><superEvent description="EPS20155" categories="teaching"><eventRules><eventRule description="EPS20155_1" startTime="18:15:00" endTime="20:45:00" note=""><recurrencePattern>EPS20155_1</recurrencePattern><attendees><attendee>Anne BrÃ¼ggemann-Klein</attendee><attendee>David Becher</attendee></attendees></eventRule></eventRules></superEvent><superEvent description="bbbb" categories="teaching"><eventRules><eventRule description="bbbb_1" startTime="12:15:00" endTime="13:45:00" note=""><recurrencePattern>bbbb_1</recurrencePattern><attendees><attendee>Test</attendee><attendee>John</attendee><attendee>Yiannis</attendee></attendees></eventRule></eventRules></superEvent><superEvent description="Test" categories="teaching"><eventRules><eventRule description="Test" startTime="10:00:00" endTime="12:00:00" note=""><recurrencePattern>
                                Test
                            </recurrencePattern><attendees><attendee>Test</attendee></attendees><location>
                                Test
                            </location></eventRule></eventRules></superEvent><superEvent description="Test_2" categories="Test_2"><eventRules><eventRule description="Test_2" startTime="10:00:00" endTime="12:00:00" note="Test"><recurrencePattern>Test_2</recurrencePattern><attendees><attendee>Tet</attendee></attendees><location>Test</location></eventRule></eventRules></superEvent><superEvent description="Tes21" categories="Test21"><eventRules><eventRule description="Tes21_1" startTime="10:00:00" endTime="12:00:00" note="Test"><recurrencePattern>Tes21_1</recurrencePattern><attendees><attendee>Test</attendee><attendee> test123</attendee></attendees><location>Test</location></eventRule></eventRules></superEvent><superEvent description="Test1223123" categories="test12312"><eventRules><eventRule description="Test1223123" startTime="10:00:00" endTime="12:00:00" note="Test"><recurrencePattern>Test1223123</recurrencePattern><attendees><attendee>Test</attendee></attendees><location>Test</location></eventRule></eventRules></superEvent><superEvent description="TEas12" categories="pd"><eventRules><eventRule description="TEas12" startTime="10:00:00" endTime="12:00:00" note="Testa"><recurrencePattern>TEas12</recurrencePattern><attendees><attendee>Tas</attendee></attendees><location>Teas</location></eventRule></eventRules></superEvent><superEvent description="Testat400" categories="dd"><eventRules><eventRule description="Testat400" startTime="10:00:00" endTime="12:00:00" note="tes"><recurrencePattern>Testat400</recurrencePattern><attendees><attendee>tes</attendee></attendees><location>tes</location></eventRule></eventRules></superEvent><superEvent description="Teasa" categories="Tes"><eventRules><eventRule description="Teasa" startTime="23:00:00" endTime="23:30:00" note="Teas"><recurrencePattern>Teasa</recurrencePattern><attendees><attendee>Tes</attendee></attendees><location>DD</location></eventRule></eventRules></superEvent><superEvent description="TesYear1" categories="test"><eventRules><eventRule description="TesYear1_1" startTime="10:00:00" endTime="12:00:00" note="Test"><recurrencePattern>TesYear1_1</recurrencePattern><attendees><attendee>Test</attendee></attendees><location>Test</location></eventRule></eventRules></superEvent><superEvent description="TestMonthOrd" categories="Test"><eventRules><eventRule description="TestMonthOrd_1" startTime="10:00:00" endTime="12:00:00" note="TT"><recurrencePattern>TestMonthOrd_1</recurrencePattern><attendees><attendee>TT</attendee></attendees><location>TT</location></eventRule></eventRules></superEvent><superEvent description="TestEndDateDisability" categories="test"><eventRules><eventRule description="TestEndDateDisability" startTime="10:00:00" endTime="12:00:00" note="test"><recurrencePattern>TestEndDateDisability</recurrencePattern><attendees><attendee>test2</attendee></attendees><location>test2</location></eventRule></eventRules></superEvent><superEvent description="TestLast" categories="test"><eventRules><eventRule description="TestLast" startTime="12:00:00" endTime="14:00:00" note="Test"><recurrencePattern>TestLast</recurrencePattern><attendees><attendee>Test</attendee></attendees><location>Test</location></eventRule></eventRules></superEvent></superEvents></calendar></calendars><patterns><differencePattern description="XMLT2015_d_1"><firstPattern>XMLT20155_1</firstPattern><furtherPatterns><furtherPattern>Feiertage2015</furtherPattern></furtherPatterns></differencePattern><intersectionPattern description="XMLT20155_1"><firstPattern>XMLT20155</firstPattern><furtherPatterns><furtherPattern>thursday</furtherPattern></furtherPatterns></intersectionPattern><unionPattern description="Feiertage2015"><firstPattern>ChrHf</firstPattern><furtherPatterns><furtherPattern>Fronleichnam</furtherPattern></furtherPatterns></unionPattern><unionPattern description="bbbb_1"><firstPattern>monday</firstPattern><furtherPatterns/></unionPattern><intersectionPattern description="EPS20155_1"><firstPattern>EPS20155</firstPattern><furtherPatterns><furtherPattern>tuesday</furtherPattern><furtherPattern>thursday</furtherPattern></furtherPatterns></intersectionPattern><dailyPattern description="ChrHf" startDate="2015-05-14" endDate="2015-05-14"/><dailyPattern description="Fronleichnam" startDate="2015-06-04" endDate="2015-06-04"/><dailyPattern description="XMLT20155" startDate="2015-04-13" endDate="2015-07-17"/><dailyPattern description="EPS20155" startDate="2015-04-13" endDate="2015-07-17"/><weeklyPattern description="monday" dayOfWeek="Monday"/><weeklyPattern description="tuesday" dayOfWeek="Tuesday"/><weeklyPattern description="wednesday" dayOfWeek="Wednesday"/><weeklyPattern description="thursday" dayOfWeek="Thursday"/><weeklyPattern description="friday" dayOfWeek="Friday"/><weeklyPattern description="saturday" dayOfWeek="Saturday"/><weeklyPattern dayOfWeek="Sunday" description="sunday"/><dailyPattern description="Test" startDate="2015-07-16" endDate="2015-08-13"/><dailyPattern description="Test_2" startDate="2015-07-22" endDate="2015-08-26"/><dailyPattern description="Tes21" startDate="2015-08-04" endDate="2015-08-11"/><unionPattern description="Tes21_1"><firstPattern>monday</firstPattern><furtherPatterns><furtherPattern>saturday</furtherPattern></furtherPatterns></unionPattern><weeklyPattern description="Teasa" dayOfWeek="Wednesday"/><cardinalYearlyPattern dayOfMonth="25" month="August" description="TesYear1"/><ordinalMonthlyPattern ordinal="first" dayType="day" description="TestMonthOrd"/><unionPattern description="TestLast"><firstPattern>monday</firstPattern><furtherPatterns><furtherPattern>tuesday</furtherPattern><furtherPattern>wednesday</furtherPattern><furtherPattern>thursday</furtherPattern><furtherPattern>friday</furtherPattern><furtherPattern>saturday</furtherPattern><furtherPattern>sunday</furtherPattern></furtherPatterns></unionPattern></patterns><users/><contacts><contact description="Anne BrÃ¼ggemann-Klein"/><contact description="David Becher"/></contacts><locations><location description="00.09.13A"/><location description="HS2"/></locations></calendarX>

=== mokshasoul/XML-Praktikum/db/apps/praktikum/data/sampleCalendarX2.xml
<calendarX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CalendarX.xsd" description="Demonstrating super events"><calendars><calendar description="Demonstrating super events"><superEvents><superEvent description="XMLT2015" categories="teaching"><eventRules><eventRule description="XMLT2015" startTime="10:15:00" endTime="12:00:00" note=""><recurrencePattern>thursdaysInS105wOFeiertage</recurrencePattern><attendees/></eventRule></eventRules></superEvent><superEvent description="EPS2015" categories="teaching"><eventRules><eventRule description="EPS2015Mo" startTime="12:15:00" endTime="13:45:00" note=""><recurrencePattern>mondaysInS2015</recurrencePattern><attendees><attendee>Anne Brüggemann-Klein</attendee><attendee>David Becher</attendee></attendees><location>00.09.13A</location></eventRule><eventRule description="EPS2015Tue" startTime="16:15:00" endTime="17:45:00" note=""><recurrencePattern>tuesdaysInS2015</recurrencePattern><attendees><attendee>Anne Brüggemann-Klein</attendee></attendees><location>HS2</location></eventRule></eventRules></superEvent><superEvent description="Test"><eventRules><eventRule description="Test" startTime="10:00" endTime="12:00" note=""><attendees><attendee/></attendees><location><location>test</location></location></eventRule></eventRules></superEvent><superEvent description="Test"><eventRules><eventRule description="Test" startTime="10:00" endTime="12:00" note=""><attendees><attendee/></attendees><location><location>test</location></location></eventRule></eventRules></superEvent></superEvents></calendar><superEvent description="Test"><eventRules><eventRule description="Test" startTime="10:00" endTime="12:00" note=""><attendees><attendee/></attendees><location><location>test</location></location></eventRule></eventRules></superEvent></calendars><patterns><differencePattern description="thursdaysInS105wOFeiertage"><firstPattern>thursdaysInS2015</firstPattern><furtherPatterns><furtherPattern>Feiertage2015</furtherPattern></furtherPatterns></differencePattern><intersectionPattern description="thursdaysInS2015"><firstPattern>S2015</firstPattern><furtherPatterns><furtherPattern>thursdays</furtherPattern></furtherPatterns></intersectionPattern><unionPattern description="Feiertage2015"><firstPattern>ChrHf</firstPattern><furtherPatterns><furtherPattern>Fronleichnam</furtherPattern></furtherPatterns></unionPattern><dailyPattern description="ChrHf" startDate="2015-05-14" endDate="2015-05-14"/><dailyPattern description="Fronleichnam" startDate="2015-06-04" endDate="2015-06-04"/><dailyPattern description="S2015" startDate="2015-04-13" endDate="2015-07-17"/><weeklyPattern description="mondays" dayOfWeek="Monday"/><weeklyPattern description="tuesdays" dayOfWeek="Tuesday"/><weeklyPattern description="thursdays" dayOfWeek="Thursday"/><intersectionPattern description="mondaysInS2015"><firstPattern>S2015</firstPattern><furtherPatterns><furtherPattern>mondays</furtherPattern></furtherPatterns></intersectionPattern><intersectionPattern description="tuesdaysInS2015"><firstPattern>S2015</firstPattern><furtherPatterns><furtherPattern>tuesdays</furtherPattern></furtherPatterns></intersectionPattern></patterns><users/><contacts><contact description="Anne Brüggemann-Klein"/></contacts><locations><location description="00.09.13A"/><location description="HS2"/></locations></calendarX>
